### ISSUE TITLE
TypeError on Mac OS+Python 2.7.10

### ISSUE THREAD

**Issue by scrow** [Ippo343/splitics#1]
Attempting `python splitics.py ical_export.ics -s 750k` returns:

```
Traceback (most recent call last):
  File "splitics.py", line 75, in <module>
    stream.write(line)
TypeError: unicode argument expected, got 'str'
```

Python version is 2.7.10

**Comment by Ippo343** [comment]
Hello @scrow , I'm afraid this script is for python3, as you can see from [the header](https://github.com/Ippo343/splitics/blob/master/splitics.py#L1).
I should probably make it more clear somewhere.

Thanks!

**Comment by scrow** [comment]
Oh, awesome, thank you for the information.  I've never dived into Python so I didn't even attempt to decipher the source aside from the specific line in question.  Python3 is installing now!  I appreciate the quick response.

**Comment by Ippo343** [comment]
No problem! Honestly it was my fault, the examples in the readme made it look like you could also use python2. I updated it so there's no ambiguity.
Let me know if it works, by the way :)

**Comment by scrow** [comment]
Yes, it worked just dandy once I used Homebrew to install Python3.  Thank you for the help.  The updated `README.md` makes it a bit more obvious, too.  I was coming from druths/icssplitter and didn't think about a difference in Python versions.

**Comment by Ippo343** [comment]
Glad I helped. Cheers!
